backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - label: "Pages"
    name: "pages"
    files:
      # ANCHOR Home Page
      - label: "Landing"
        name: "landing"
        file: "content/pages/landing.md"
        preview: false
        fields:
          - {
              label: "Template Key",
              name: template_key,
              widget: hidden,
              default: index_page,
            }
          - label: "Hero - The full screen image with tagline and main button"
            name: hero
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Subtitle, name: subtitle, widget: string }
              - { label: Tagline, name: tagline, widget: string }
              - { label: Description, name: description, widget: text }
              - {
                  label: "Cover-Image - Full screen image",
                  name: coverImage,
                  widget: image,
                }
              - label: "CTA (Call to Action) This is centered button on page"
                name: cta
                widget: object
                fields:
                  - { label: CTA-Text, name: cta_text, widget: string }
                  - { label: CTA-Link, name: cta_link, widget: string }

          # Intro Section
          - label: "Intro - Second section"
            name: intro
            widget: object
            fields:
              - { label: "Intro Title", name: intro_title, widget: string }
              - { label: "Intro Heading", name: intro_heading, widget: string }
              - { label: "Intro Body", name: intro_body, widget: markdown }
              - { label: "Intro Image", name: intro_image, widget: image }
              # Blurbs
              # Blurb1
              - {
                  label: "Blurb 1 Heading",
                  name: blurb1_heading,
                  widget: string,
                }
              - { label: "Blurb 1 image", name: blurb1_image, widget: image }
              - { label: "Blurb 1 text", name: blurb1_text, widget: markdown }

              # Blurb2
              - {
                  label: "Blurb 2 Heading",
                  name: blurb2_heading,
                  widget: string,
                }
              - { label: "Blurb 2 image", name: blurb2_image, widget: image }
              - { label: "Blurb 2 text", name: blurb2_text, widget: markdown }

              # Blurb3
              - {
                  label: "Blurb 3 Heading",
                  name: blurb3_heading,
                  widget: string,
                }
              - { label: "Blurb 3 image", name: blurb3_image, widget: image }
              - { label: "Blurb 3 text", name: blurb3_text, widget: markdown }

          # Our Family section
          - label: "Our Family"
            name: our_family
            widget: object
            fields:
              - label: "Our Family section title"
                name: our_family_title
                widget: string
              - label: "Our Family section subtitle"
                name: our_family_subtitle
                widget: string
              - label: "Our Family section - photos"
                name: our_family_photos
                widget: list
                fields:
                  - {
                      label: "Dog Name",
                      name: our_family_dog_name,
                      widget: string,
                    }
                  - {
                      label: "Dog Image",
                      name: our_family_dog_image,
                      widget: image,
                    }
                  - {
                      label: "About Dog",
                      name: our_family_about_dog,
                      widget: markdown,
                    }

          - label: "Gallery"
            name: "gallery"
            widget: object
            fields:
              - { label: "Gallery Title", name: gallery_title, widget: string }
              - {
                  label: "Gallery Subtitle",
                  name: gallery_subtitle,
                  widget: string,
                }
              - label: "Gallery Photos"
                name: gallery_photos
                widget: list
                fields:
                  - {
                      label: "Gallery Image",
                      name: "gallery_image",
                      widget: image,
                    }
                  - {
                      label: "Alt Text - (brief description of image)",
                      name: "gallery_image_alt_text",
                      widget: string,
                    }

      # ANCHOR About Page
      - label: About
        name: about
        file: "content/pages/about.md"
        preview: false
        fields:
          - label: "Template Key"
            name: template_key
            widget: hidden
            default: about_page

          - label: Banner
            name: banner
            widget: object
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Subtitle, name: subtitle, widget: markdown }
              - { label: "Banner Image", name: image, widget: image }

          - label: "Articles - 3 articles looks best"
            name: articles
            widget: list
            fields:
              - label: Article
                name: article
                widget: object
                fields:
                  - { label: Heading, name: heading, widget: string }
                  - { label: Content, name: content, widget: markdown }
                  - { label: Image, name: image, widget: image }

          - label: "Contact parallax"
            name: contact_parallax
            widget: object
            fields:
              - { label: Image, name: image, widget: image }
              - {
                  label: "Show Parallax",
                  name: show,
                  widget: boolean,
                  default: true,
                }

      # ANCHOR Our Dogs Page
      - label: Our Dogs
        name: our-dogs
        file: "content/pages/our-dogs.md"
        fields:
          - label: "Template Key"
            name: template_key
            widget: hidden
            default: our_dogs_page

          - label: Banner
            name: banner
            widget: object
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Subtitle, name: subtitle, widget: markdown }
              - { label: "Banner Image", name: image, widget: image }
          - label: "Articles - At least 3 articles looks best"
            name: "articles"
            widget: list
            fields:
              - label: Article
                name: article
                widget: object
                fields:
                  - { label: Heading, name: heading, widget: string }
                  - { label: Content, name: content, widget: markdown }
                  - { label: Image, name: image, widget: image }
          - label: "Contact parallax"
            name: contact_parallax
            widget: object
            fields:
              - { label: Image, name: image, widget: image }
              - {
                  label: "Show Parallax",
                  name: show,
                  widget: boolean,
                  default: true,
                }
      # ANCHOR faqs Page
      - label: FAQS
        name: FAQS
        file: "content/pages/faqs.md"
        fields:
          - label: "Template Key"
            name: template_key
            widget: hidden
            default: faqs_page

          - label: Banner
            name: banner
            widget: object
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Subtitle, name: subtitle, widget: markdown }
              - { label: "Banner Image", name: image, widget: image }
          - label: FAQS
            name: faqs
            widget: list
            fields:
              - label: FAQ
                name: faq
                widget: object
                fields:
                  - { label: Question, name: question, widget: string }
                  - { label: Answer, name: answer, widget: markdown }
          - label: "Contact parallax"
            name: contact_parallax
            widget: object
            fields:
              - { label: Image, name: image, widget: image }
              - {
                  label: "Show Parallax",
                  name: show,
                  widget: boolean,
                  default: true,
                }

      # ANCHOR Puppies page
      - label: Puppies
        name: puppies_page
        file: "content/pages/puppies.md"
        fields:
          - label: "Template Key"
            name: template_key
            widget: hidden
            default: puppies_page
          - label: Banner
            name: banner
            widget: object
            fields:
              - { label: Heading, name: heading, widget: string }
              - { label: Subtitle, name: subtitle, widget: markdown }
              - { label: "Banner Image", name: image, widget: image }

          - label: "Contact parallax"
            name: contact_parallax
            widget: object
            fields:
              - { label: Image, name: image, widget: image }
              - {
                  label: "Show Parallax",
                  name: show,
                  widget: boolean,
                  default: true,
                }

          # ANCHOR Litter
          - label: Litters
            name: litters
            widget: list
            fields:
              - {
                  label: Date of Birth,
                  name: dob,
                  widget: datetime,
                  date_format: "dd.MM.yyyy",
                  time_format: false,
                  format: "yyyy-MM-dd",
                }
              - { label: Description, name: description, widget: markdown }
              - {
                  label: Latest,
                  name: latest,
                  widget: boolean,
                  default: false,
                  hint: This will be the first litter shown on the page.,
                }
              - label: Parents
                name: parents
                widget: object
                fields:
                  - label: Male
                    name: male
                    widget: object
                    fields:
                      - { label: Name, name: name, widget: string, default: "" }
                      - { label: Image, name: image, widget: image }
                      - {
                          label: Blurb,
                          name: text,
                          widget: markdown,
                          hint: Brief description of dog,
                        }
                  - label: Female
                    name: female
                    widget: object
                    fields:
                      - { label: Name, name: name, widget: string, default: "" }
                      - { label: Image, name: image, widget: image }
                      - {
                          label: Blurb,
                          name: text,
                          widget: markdown,
                          hint: Brief description of dog,
                        }

              # ANCHOR Litter - Pups
              - label: Puppies
                name: puppies
                widget: object
                fields:
                  - label: Puppy
                    name: puppy
                    widget: list
                    fields:
                      - { label: Name, name: name, widget: string }
                      - { label: Color, name: color, widget: string }
                      - { label: Sex, name: sex, widget: string }
                      - {
                          label: Description,
                          name: description,
                          widget: markdown,
                        }
                      - {
                          label: Sold,
                          name: sold,
                          widget: boolean,
                          default: false,
                        }
                      - {
                          label: Reserved,
                          name: reserved,
                          widget: boolean,
                          default: false,
                        }
                      - label: Personality
                        name: personality
                        widget: object
                        fields:
                          - {
                              label: Shyness,
                              name: shyness,
                              widget: number,
                              min: 1,
                              max: 10,
                              default: 5,
                              hint: 1 = shy,
                              10 = outgoing,
                            }
                          - {
                              label: Playfulness,
                              name: playfulness,
                              widget: number,
                              min: 1,
                              max: 10,
                              default: 5,
                              hint: 1 = lazy,
                              10 = playful,
                            }
                          - {
                              label: Trainaility,
                              name: trainability,
                              widget: number,
                              min: 1,
                              max: 10,
                              default: 5,
                              hint: 1 = stubborn,
                              10 = easy to train,
                            }
                          - {
                              label: Affectionate,
                              name: affectionate,
                              widget: number,
                              min: 1,
                              max: 10,
                              default: 5,
                              hint: 1 = aloof,
                              10 = cuddly,
                            }
                          - {
                              label: Energetic,
                              name: energetic,
                              widget: number,
                              min: 1,
                              max: 10,
                              default: 5,
                              hint: 1 = couch potato,
                              10 = high energy,
                            }
                      - label: Images
                        name: images
                        widget: list
                        fields:
                          - label: Image
                            name: image
                            widget: object
                            fields:
                              - { label: Image, name: image, widget: image }
                              - {
                                  label: Alt Text,
                                  name: alt_text,
                                  widget: string,
                                }

          - label: Upcoming Litters
            name: upcoming_litters
            required: false
            default: false
            widget: list
            fields:
              - label: Estimated Date of Birth
                name: eta
                widget: datetime
                date_format: "MM.yyyy"
                time_format: false
                format: "yyyy-MM"
              - {
                  label: Description,
                  name: description,
                  widget: markdown,
                  hint: Brief blurb of upcoming litter,
                }
              - label: Parents
                name: parents
                widget: object
                fields:
                  - label: Male
                    name: male
                    widget: object
                    fields:
                      - { label: Name, name: name, widget: string }
                      - { label: Image, name: image, widget: image }
                      - {
                          label: Blurb,
                          name: text,
                          widget: markdown,
                          hint: Brief description of dog,
                        }
                  - label: Female
                    name: female
                    widget: object
                    fields:
                      - { label: Name, name: name, widget: string }
                      - { label: Image, name: image, widget: image }
                      - {
                          label: Blurb,
                          name: text,
                          widget: markdown,
                          hint: Brief description of dog,
                        }

  - label: "Site Settings"
    name: site_settings
    files:
      - label: Settings
        name: settings
        file: "static/site-settings.md"
        fields:
          - label: Settings_File
            name: settings_file
            widget: hidden
            default: "settings_file"

          - label: "Global Title"
            name: global_title
            widget: string
          - label: Logo
            name: logo
            widget: image
            media_library:
              config:
                multiple: false
          - label: "Dark Mode"
            name: dark_mode
            widget: boolean
            required: false
            default: false
          - label: "Accent Color"
            name: accent_color
            widget: color
            enabledAlpha: true
            allowInput: true

  # ANCHOR Disclaimer
  - label: Disclaimer
    name: disclaimer
    files:
      - label: Disclaimer
        name: disclaimer
        file: "content/disclaimer.md"
        fields:
          - label: Disclaimer
            name: disclaimer
            widget: markdown
